### PR TITLE
fix: compare BigDecimal by compareTo

### PR DESCRIPTION
**Pull request by dowenliu-xyz**

### CODE REVIEW

**Comment by jansorg** [comment]
Thanks! I'd prefer to introduce an extension function or property `fun BigDecimal.isZero()` which uses the comparator as suggested by your PR. If you like, adding it at  `dev.ja.marketplace.util` in the `marketplace-data` module should work.
Otherwise I'll push a change to fix this.

**Comment by dowenliu-xyz** [comment]
> Thanks! I'd prefer to introduce an extension function or property `fun BigDecimal.isZero()` which uses the comparator as suggested by your PR. If you like, adding it at `dev.ja.marketplace.util` in the `marketplace-data` module should work. Otherwise I'll push a change to fix this.

Updated.

**Comment by jansorg** [comment]
Thanks! 
Is a new release need for this fix, i.e. did you observe incorrect results in the UI without this change?

**Comment by dowenliu-xyz** [comment]
I had got a 500 response when I run in docker. And then I cloned this repo and did this fix.
I think a new release is need, at least, a new docker image.

**Comment by jansorg** [comment]
Was the 500 response related to this change? That's unlikely, but I'll make a new release nontheless.

**Comment by dowenliu-xyz** [comment]
I checkout commit `182ce42c03d9923e8359623b6e4035f0747edee5` and rerun. Here is the error log:
```
22:02:26.622 ERROR ktor.application - Unhandled: GET - /
gg.jte.TemplateException: Failed to render main.kte, error at dataTable.kte:10
	at gg.jte.TemplateEngine.handleRenderException(TemplateEngine.java:259)
	at gg.jte.TemplateEngine.render(TemplateEngine.java:232)
	at io.ktor.server.jte.JteKt$Jte$2$1.invokeSuspend(Jte.kt:53)
	at io.ktor.server.jte.JteKt$Jte$2$1.invoke(Jte.kt)
	at io.ktor.server.jte.JteKt$Jte$2$1.invoke(Jte.kt)
	at io.ktor.server.application.hooks.BeforeResponseTransform$install$1.invokeSuspend(CommonHooks.kt:149)
	at io.ktor.server.application.hooks.BeforeResponseTransform$install$1.invoke(CommonHooks.kt)
	at io.ktor.server.application.hooks.BeforeResponseTransform$install$1.invoke(CommonHooks.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:120)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:78)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute$ktor_utils(SuspendFunctionGun.kt:98)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:77)
	at dev.ja.marketplace.MarketplaceStatsServer$httpServer$1$3$2.invokeSuspend(MarketplaceStatsServer.kt:416)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:343)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:135)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:109)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:11)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:59)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$lambda$0(NettyApplicationEngine.kt:296)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.lang.ArithmeticException: / by zero
	at java.base/java.math.BigDecimal.divideAndRound(BigDecimal.java:4675)
	at java.base/java.math.BigDecimal.divide(BigDecimal.java:5748)
	at java.base/java.math.BigDecimal.divide(BigDecimal.java:1650)
Caused by: java.lang.ArithmeticException: / by zero

	at java.base/java.math.BigDecimal.divide(BigDecimal.java:1680)
	at dev.ja.marketplace.data.PercentageValue$Companion.of(types.kt:25)
	at dev.ja.marketplace.data.customerType.CustomerTypeTable.createSections(CustomerTypeTable.kt:35)
	at dev.ja.marketplace.data.SimpleDataTable$sections$2.invoke(DataTable.kt:56)
	at dev.ja.marketplace.data.SimpleDataTable$sections$2.invoke(DataTable.kt:56)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at dev.ja.marketplace.data.SimpleDataTable.getSections(DataTable.kt:56)
	at gg.jte.generated.precompiled.JtedataTableGenerated$Companion.render(dataTable.kte:10)
	at gg.jte.generated.precompiled.JtemainGenerated$Companion.render(main.kte:50)
	at gg.jte.generated.precompiled.JtemainGenerated$Companion.renderMap(main.kte:16)
	at gg.jte.generated.precompiled.JtemainGenerated.renderMap(main.kte:0)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at gg.jte.runtime.Template.renderMap(Template.java:58)
	at gg.jte.TemplateEngine.render(TemplateEngine.java:230)
	... 33 common frames omitted
```

**Comment by jansorg** [comment]
I see, fixing a divide a zero makes sense. 
I've released 0.15.5, which includes the docker container.

**Pull request merged**
